services:
  db:
    image: postgres:18-alpine
    container_name: gptbundle_db_dev
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gptbundle
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    restart: unless-stopped
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    ports:
      - "9000:8000"
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data/

volumes:
  postgres_data:
  dynamodb-data:
