secrets:
  openrouter_api_key:
    environment: OPENROUTER_API_KEY
  jwt_secret_key:
    environment: JWT_SECRET_KEY
  s3_access_key_id:
    environment: S3_ACCESS_KEY_ID
  s3_secret_access_key:
    environment: S3_SECRET_ACCESS_KEY

services:
  web:
    build: .
    container_name: gptbundle
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gptbundle
      - POSTGRES_HOST=db
      - AWS_ENDPOINT_URL_DYNAMODB=http://dynamodb-local:8000
      - AWS_ACCESS_KEY_ID=TEST
      - AWS_SECRET_ACCESS_KEY=TEST
      - DEVELOPMENT_MODE=false
      - ALLOW_REGISTRATION=false
      - S3_ENDPOINT_URL=https://s3.eu-central-1.amazonaws.com
      - SUBDIRECTORY=gptbundle
    depends_on:
      - db
      - dynamodb-local
      - elasticsearch
    secrets:
      - openrouter_api_key
      - jwt_secret_key
      - s3_access_key_id
      - s3_secret_access_key

  db:
    image: postgres:18-alpine
    container_name: gptbundle_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gptbundle
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    restart: unless-stopped
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    ports:
      - "9000:8000"
    volumes:
      - ./dynamodb_data:/home/dynamodblocal/data/

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.1
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changemepls
      - "ELASTICSEARCH_USERNAME=elastic"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  postgres_data:
  dynamodb_data:
  esdata:
