services:
  db:
    image: postgres:18-alpine
    container_name: gptbundle_db_dev
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gptbundle
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    restart: unless-stopped
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    ports:
      - "9000:8000"
    volumes:
      - ./dynamodb_data_dev:/home/dynamodblocal/data/

  minio:
    image: minio/minio
    container_name: minio
    restart: unless-stopped
    ports:
      - "9001:9001"
      - "9002:9000"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.1
    container_name: elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=changemepls
      - "ELASTICSEARCH_USERNAME=elastic"
    ports:
      - "9200:9200"
    volumes:
      - esdata-dev:/usr/share/elasticsearch/data

volumes:
  postgres_data_dev:
  dynamodb_data_dev:
  minio_data:
  esdata-dev:
