secrets:
  openrouter_api_key:
    environment: OPENROUTER_API_KEY
  jwt_secret_key:
    environment: JWT_SECRET_KEY

services:
  web:
    build: .
    container_name: gptbundle
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gptbundle
      - POSTGRES_HOST=db
      - AWS_ENDPOINT_URL_DYNAMODB=http://dynamodb-local:8000
      - AWS_ACCESS_KEY_ID=TEST
      - AWS_SECRET_ACCESS_KEY=TEST
      - DEVELOPMENT_MODE=false
    depends_on:
      - db
      - dynamodb-local
    secrets:
      - openrouter_api_key
      - jwt_secret_key

  db:
    image: postgres:18-alpine
    container_name: gptbundle_db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gptbundle
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    restart: unless-stopped
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /home/dynamodblocal/data/"
    ports:
      - "9000:8000"
    volumes:
      - ./dynamodb-data:/home/dynamodblocal/data/

volumes:
  postgres_data:
  dynamodb-data:
